//note that the Name must be unique, regardess of what category it is in
var checklistData = [ 
{Name:"Water: 72 hour supply, 2 litres per person", Category:"Basic"},
{Name:"Food: 72 hour supply", Category:"Basic"},
{Name:"Basic: First aid kit ", Category:"Basic"},
{Name:"Basic: Eye glasses ", Category:"Basic"},
{Name:"Basic: Cane", Category:"Basic"},
{Name:"Basic: Hearing aid with extra batteries ", Category:"Basic"},
{Name:"Basic: Sturdy shoes", Category:"Basic"},
{Name:"Basic: Change of clothes ", Category:"Basic"},
{Name:"Basic: Flashlight / Batteries", Category:"Basic"},
{Name:"Basic: Portable AM/FM radio / Batteries", Category:"Basic"},
{Name:"Basic: Candles", Category:"Basic"},
{Name:"Basic: Waterproof Matches ", Category:"Basic"},
{Name:"Basic: Non-electric can opener ", Category:"Basic"},
{Name:"Basic: Knife (Swiss army knife) ", Category:"Basic"},
{Name:"Basic: Solar blankets ", Category:"Basic"},
{Name:"Basic: Whistle", Category:"Basic"},
{Name:"Basic: Essential insurance papers, identification ", Category:"Basic"},
{Name:"Basic: Sanitation Supplies ", Category:"Basic"},
{Name:"Basic: Large plastic trash bags - for trash waste, water protection, ground cloth ", Category:"Basic"},
{Name:"Basic: Bar soap ", Category:"Basic"},
{Name:"Basic: Liquid detergent ", Category:"Basic"},
{Name:"Basic: Shampoo", Category:"Basic"},
{Name:"Basic: Toothpaste & toothbrushes ", Category:"Basic"},
{Name:"Basic: Pre-moistened towelettes", Category:"Basic"},
{Name:"Basic: Deodorant", Category:"Basic"},
{Name:"Basic: Denture cleanser ", Category:"Basic"},
{Name:"Basic: Feminine supplies ", Category:"Basic"},
{Name:"Basic: Toilet paper ", Category:"Basic"},
{Name:"Basic: Powdered chlorinate lime - add to sewage to deodorize, disinfect and keep away insects", Category:"Basic"},
{Name:"Basic: Household bleach ", Category:"Basic"},
{Name:"Basic: Cooking Supplies ", Category:"Basic"},
{Name:"Basic: Barbeque - hibachi, camp stove", Category:"Basic"},
{Name:"Basic: Fuel for cooking equipment", Category:"Basic"},
{Name:"Basic: Plastic knives, forks, spoons ", Category:"Basic"},
{Name:"Basic: Paper plates and cups ", Category:"Basic"},
{Name:"Basic: Paper towels ", Category:"Basic"},
{Name:"Basic: Heavy duty aluminum foil ", Category:"Basic"},
{Name:"Car: Sturdy Shoes", Category:"Car Survival Kit"},
{Name:"Car: Extra Clothes", Category:"Car Survival Kit"},
{Name:"Car: First aid kit", Category:"Car Survival Kit"},
{Name:"Car: Essential medication", Category:"Car Survival Kit"},
{Name:"Car: Water", Category:"Car Survival Kit"},
{Name:"Car: Pre-moistened towelettes ", Category:"Car Survival Kit"},
{Name:"Car: Tissue paper", Category:"Car Survival Kit"},
{Name:"Car: Flashlight / Batteries ", Category:"Car Survival Kit"},
{Name:"Car: Portable AM/FM radio / Batteries ", Category:"Car Survival Kit"},
{Name:"Car: Non-perishable food (granola bars) ", Category:"Car Survival Kit"},
{Name:"Car: Knife", Category:"Car Survival Kit"},
{Name:"Car: Waterproof Matches / Candles ", Category:"Car Survival Kit"},
{Name:"Car: Solar Blanket ", Category:"Car Survival Kit"},
{Name:"Car: Whistle", Category:"Car Survival Kit"},
{Name:"Car: Magnifying glass", Category:"Car Survival Kit"},
{Name:"Car: Local map ", Category:"Car Survival Kit"},
{Name:"Tools: Crescent wrench - for turning off gas main", Category:"Tools"},
{Name:"Tools: Ax", Category:"Tools"},
{Name:"Tools: Shovel", Category:"Tools"},
{Name:"Tools: Screwdriver", Category:"Tools"},
{Name:"Tools: Pliers", Category:"Tools"},
{Name:"Tools: Hammer", Category:"Tools"},
{Name:"Tools: Coil of 1/2 inch rope ", Category:"Tools"},
{Name:"Tools: Coil of baling wire ", Category:"Tools"},
{Name:"Tools: Plastic tape ", Category:"Tools"},
{Name:"Tools: Plastic sheeting ", Category:"Tools"},
{Name:"Tools: Pen and paper ", Category:"Tools"},
{Name:"Infants: Diapers", Category:"Infants"},
{Name:"Infants: Medications", Category:"Infants"},
{Name:"Infants: Bottles & Formula", Category:"Infants"},
{Name:"Pets: Portable carrier or crate ", Category:"Pets"},
{Name:"Pets: Combination food & water dish ", Category:"Pets"},
{Name:"Pets: One weeks supply of food", Category:"Pets"},
{Name:"Pets: Kitty litter and box ", Category:"Pets"},
{Name:"Pets: Favourite treat or toy ", Category:"Pets"},
{Name:"Pets: Current colour photographs ", Category:"Pets"},
{Name:"Pets: Extra leashes ", Category:"Pets"},
{Name:"Pets: Health and vaccination records ", Category:"Pets"},
{Name:"Pets: Supply of regular medicines ", Category:"Pets"},
{Name:"Pets: Blanket, towels or pet bed", Category:"Pets"},
{Name:"Pets: Clean-up materials", Category:"Pets"}
];
